/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fl.flgamesdkexample;

public final class R {
    public static final class anim {
        public static final int flsdk_left_in=0x7f040000;
        public static final int flsdk_left_out=0x7f040001;
        public static final int flsdk_right_in=0x7f040002;
        public static final int flsdk_right_out=0x7f040003;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int flsdk_btn_green_text_color=0x7f060014;
        public static final int flsdk_btn_yellow_text_color=0x7f060015;
        public static final int flsdk_gamehelper_color_00323a=0x7f060003;
        public static final int flsdk_gamehelper_color_077df7=0x7f060013;
        public static final int flsdk_gamehelper_color_1b4503=0x7f060006;
        public static final int flsdk_gamehelper_color_2b261c=0x7f060004;
        /**  -输入框字体色 
         */
        public static final int flsdk_gamehelper_color_353535=0x7f06000f;
        public static final int flsdk_gamehelper_color_383838=0x7f06000d;
        public static final int flsdk_gamehelper_color_494e54=0x7f060011;
        public static final int flsdk_gamehelper_color_50translucent=0x7f060002;
        public static final int flsdk_gamehelper_color_654208=0x7f060005;
        public static final int flsdk_gamehelper_color_9a9a9a=0x7f06000b;
        public static final int flsdk_gamehelper_color_b0b0b0=0x7f060010;
        public static final int flsdk_gamehelper_color_c12c20=0x7f060009;
        public static final int flsdk_gamehelper_color_c2c2c2=0x7f06000a;
        /** 登录界面 -下拉 选 中文字背景 
         */
        public static final int flsdk_gamehelper_color_c4c4c4=0x7f060012;
        public static final int flsdk_gamehelper_color_d5bf00=0x7f060007;
        public static final int flsdk_gamehelper_color_f1e74b=0x7f06000e;
        public static final int flsdk_gamehelper_color_f7d98b=0x7f060008;
        public static final int flsdk_gamehelper_color_translucent=0x7f060001;
        public static final int flsdk_gamehelper_color_transparent=0x7f06000c;
        public static final int flsdk_gamehelper_color_white=0x7f060000;
        public static final int flsdk_manager_account_text_color=0x7f060016;
    }
    public static final class drawable {
        public static final int change_account=0x7f020000;
        public static final int flsdk_account_line=0x7f020001;
        public static final int flsdk_account_manager_arrow=0x7f020002;
        public static final int flsdk_account_manager_bottom=0x7f020003;
        public static final int flsdk_account_manager_focus_click_up=0x7f020004;
        public static final int flsdk_account_manager_focus_down=0x7f020005;
        public static final int flsdk_account_manager_round_botom_select=0x7f020006;
        public static final int flsdk_account_manager_round_up_select=0x7f020007;
        public static final int flsdk_alert_body_bg=0x7f020008;
        public static final int flsdk_alert_cancel_button=0x7f020009;
        public static final int flsdk_alert_ok_button=0x7f02000a;
        public static final int flsdk_body_bg=0x7f02000b;
        public static final int flsdk_btn_blue_bg=0x7f02000c;
        public static final int flsdk_btn_blue_normal_bg=0x7f02000d;
        public static final int flsdk_btn_blue_pressed_bg=0x7f02000e;
        public static final int flsdk_btn_green_bg=0x7f02000f;
        public static final int flsdk_btn_green_normal_bg=0x7f020010;
        public static final int flsdk_btn_green_pressed_bg=0x7f020011;
        public static final int flsdk_btn_unabled_bg=0x7f020012;
        public static final int flsdk_btn_yellow_bg=0x7f020013;
        public static final int flsdk_btn_yellow_normal_bg=0x7f020014;
        public static final int flsdk_btn_yellow_pressed_bg=0x7f020015;
        public static final int flsdk_checkbox_bg=0x7f020016;
        public static final int flsdk_checkbox_checked_bg=0x7f020017;
        public static final int flsdk_checkbox_unchecked_bg=0x7f020018;
        public static final int flsdk_clear_btn_bg=0x7f020019;
        public static final int flsdk_clear_btn_normal=0x7f02001a;
        public static final int flsdk_clear_btn_pressed=0x7f02001b;
        public static final int flsdk_divide_line=0x7f02001c;
        public static final int flsdk_drop_account_edit_bg=0x7f02001d;
        public static final int flsdk_drop_builder_bg=0x7f02001e;
        public static final int flsdk_drop_bulider_item_bg=0x7f02001f;
        public static final int flsdk_edit_text_bg=0x7f020020;
        public static final int flsdk_function_account_bg=0x7f020021;
        public static final int flsdk_function_announce_bg=0x7f020022;
        public static final int flsdk_function_arrow_bg=0x7f020023;
        public static final int flsdk_function_bg_normal=0x7f020024;
        public static final int flsdk_function_bg_pressed=0x7f020025;
        public static final int flsdk_function_click_expand_bg=0x7f020026;
        public static final int flsdk_function_click_shrink_bg=0x7f020027;
        public static final int flsdk_function_client_bg=0x7f020028;
        public static final int flsdk_function_content_bg=0x7f020029;
        public static final int flsdk_function_expand_bg=0x7f02002a;
        public static final int flsdk_function_expand_normal_bg=0x7f02002b;
        public static final int flsdk_function_expand_pressed_bg=0x7f02002c;
        public static final int flsdk_function_invite_code_bg=0x7f02002d;
        public static final int flsdk_function_invite_friend_bg=0x7f02002e;
        public static final int flsdk_function_msg_tips_bg=0x7f02002f;
        public static final int flsdk_function_shrink_bg=0x7f020030;
        public static final int flsdk_function_shrink_normal_bg=0x7f020031;
        public static final int flsdk_function_shrink_pressed_bg=0x7f020032;
        public static final int flsdk_icon_qq_bg=0x7f020033;
        public static final int flsdk_icon_sina_bg=0x7f020034;
        public static final int flsdk_invitation_code_bg=0x7f020035;
        public static final int flsdk_invitation_copy_normal_bg=0x7f020036;
        public static final int flsdk_invitation_copy_pressed_bg=0x7f020037;
        public static final int flsdk_invitation_num_pressed_bg=0x7f020038;
        public static final int flsdk_invite_friend_bg=0x7f020039;
        public static final int flsdk_invite_friend_copy_bg=0x7f02003a;
        public static final int flsdk_invite_friend_copy_btn_bg=0x7f02003b;
        public static final int flsdk_invite_friend_copy_normal=0x7f02003c;
        public static final int flsdk_invite_friend_copy_pressed=0x7f02003d;
        public static final int flsdk_loading_progressbar_bg=0x7f02003e;
        public static final int flsdk_loading_progressbar_image=0x7f02003f;
        public static final int flsdk_main_bg_port=0x7f020040;
        public static final int flsdk_manager_account_switch_image=0x7f020041;
        public static final int flsdk_more_arrow_bg=0x7f020042;
        public static final int flsdk_more_arrow_normal_bg=0x7f020043;
        public static final int flsdk_more_arrow_pressed_bg=0x7f020044;
        public static final int flsdk_qq_image_normal_bg=0x7f020045;
        public static final int flsdk_qq_image_pressed_bg=0x7f020046;
        public static final int flsdk_register_list_header_image_bg=0x7f020047;
        public static final int flsdk_sina_image_normal_bg=0x7f020048;
        public static final int flsdk_sina_image_pressed_bg=0x7f020049;
        public static final int flsdk_third_sina_bg=0x7f02004a;
        public static final int flsdk_third_sina_btn_cancel=0x7f02004b;
        public static final int flsdk_third_sina_btn_sure=0x7f02004c;
        public static final int flsdk_third_sina_comment_icon=0x7f02004d;
        public static final int flsdk_third_sina_logo=0x7f02004e;
        public static final int flsdk_third_sina_pop_bg=0x7f02004f;
        public static final int flsdk_third_sina_share_icon=0x7f020050;
        public static final int flsdk_third_sina_user_icon=0x7f020051;
        public static final int flsdk_title_back_bg=0x7f020052;
        public static final int flsdk_title_back_normal_bg=0x7f020053;
        public static final int flsdk_title_back_pressed_bg=0x7f020054;
        public static final int flsdk_title_bg=0x7f020055;
        public static final int flsdk_title_right_bg=0x7f020056;
        public static final int flsdk_title_right_normal_bg=0x7f020057;
        public static final int flsdk_title_right_pressed_bg=0x7f020058;
        public static final int flsdk_toast_bg=0x7f020059;
        public static final int flsdk_transparent=0x7f02005a;
        public static final int ic_launcher=0x7f02005b;
    }
    public static final class id {
        public static final int account_login_button=0x7f0a0004;
        public static final int autologin_checkBox=0x7f0a0005;
        public static final int btn_exit=0x7f0a0073;
        public static final int btn_show=0x7f0a0068;
        public static final int fldk_loginBtn=0x7f0a005f;
        public static final int flsdk_account_name_text=0x7f0a003d;
        public static final int flsdk_animator_bottom=0x7f0a006a;
        public static final int flsdk_band_code_lay=0x7f0a0010;
        public static final int flsdk_band_num_lay=0x7f0a000e;
        public static final int flsdk_base_edit=0x7f0a0015;
        public static final int flsdk_base_edit_title=0x7f0a0014;
        public static final int flsdk_btn_account_mannager=0x7f0a006f;
        public static final int flsdk_btn_announce=0x7f0a006b;
        public static final int flsdk_btn_custom_service=0x7f0a006c;
        public static final int flsdk_btn_invite_code=0x7f0a006e;
        public static final int flsdk_btn_invite_friend=0x7f0a006d;
        public static final int flsdk_btn_show=0x7f0a0067;
        public static final int flsdk_drop_builder_list=0x7f0a001e;
        public static final int flsdk_drop_builder_text=0x7f0a001d;
        public static final int flsdk_editpwd_check_lay=0x7f0a0023;
        public static final int flsdk_editpwd_new_lay=0x7f0a0020;
        public static final int flsdk_editpwd_new_tip=0x7f0a0021;
        public static final int flsdk_editpwd_old_lay=0x7f0a001f;
        public static final int flsdk_editpwd_sure_lay=0x7f0a0022;
        public static final int flsdk_findpwd_account_edit_lay=0x7f0a0024;
        public static final int flsdk_findpwd_band_edit_lay=0x7f0a0025;
        public static final int flsdk_function_account_image=0x7f0a002e;
        public static final int flsdk_function_all_tips=0x7f0a0031;
        public static final int flsdk_function_announce_image=0x7f0a0027;
        public static final int flsdk_function_announce_tips=0x7f0a0028;
        public static final int flsdk_function_client_image=0x7f0a0029;
        public static final int flsdk_function_client_tips=0x7f0a002a;
        public static final int flsdk_function_content_view=0x7f0a0032;
        public static final int flsdk_function_detail_lay=0x7f0a0026;
        public static final int flsdk_function_icon_image=0x7f0a0033;
        public static final int flsdk_function_invitate_friend_image=0x7f0a002b;
        public static final int flsdk_function_invitation_code_image=0x7f0a002d;
        public static final int flsdk_function_invite_tips=0x7f0a002c;
        public static final int flsdk_function_open_image=0x7f0a0030;
        public static final int flsdk_function_open_lay=0x7f0a002f;
        public static final int flsdk_functionview=0x7f0a0060;
        public static final int flsdk_game_alert_builder_body_lay=0x7f0a0006;
        public static final int flsdk_game_alert_builder_cancelbut=0x7f0a0009;
        public static final int flsdk_game_alert_builder_centerBtn=0x7f0a000a;
        public static final int flsdk_game_alert_builder_okbut=0x7f0a0008;
        public static final int flsdk_game_alert_builer_message=0x7f0a0007;
        public static final int flsdk_game_tool_bar_lizhize=0x7f0a0074;
        public static final int flsdk_invitation_code_lay=0x7f0a0035;
        public static final int flsdk_invitation_code_textview=0x7f0a0037;
        public static final int flsdk_invitation_copy_textview=0x7f0a0038;
        public static final int flsdk_invitation_image_webview=0x7f0a0034;
        public static final int flsdk_invitation_num_textview=0x7f0a0036;
        public static final int flsdk_invitation_rule_webview=0x7f0a0039;
        public static final int flsdk_loading_bar=0x7f0a0018;
        public static final int flsdk_loading_bar_bg=0x7f0a0017;
        public static final int flsdk_loading_error_image=0x7f0a0019;
        public static final int flsdk_login_account_lay=0x7f0a000b;
        public static final int flsdk_login_account_text=0x7f0a000d;
        public static final int flsdk_login_account_title=0x7f0a000c;
        public static final int flsdk_login_forget_pwd_btn=0x7f0a003f;
        public static final int flsdk_login_login_btn=0x7f0a003b;
        public static final int flsdk_login_more_text=0x7f0a003a;
        public static final int flsdk_login_pwd_check_lay=0x7f0a0040;
        public static final int flsdk_login_pwd_checkbox=0x7f0a0013;
        public static final int flsdk_login_pwd_lay=0x7f0a003e;
        public static final int flsdk_login_register_btn=0x7f0a003c;
        public static final int flsdk_login_rember_text=0x7f0a0012;
        public static final int flsdk_manager_account_band=0x7f0a004d;
        public static final int flsdk_manager_account_band_hide=0x7f0a0047;
        public static final int flsdk_manager_account_band_layout=0x7f0a004c;
        public static final int flsdk_manager_account_band_tips=0x7f0a004e;
        public static final int flsdk_manager_account_editpwd=0x7f0a0045;
        public static final int flsdk_manager_account_level=0x7f0a004b;
        public static final int flsdk_manager_account_modify_pwd=0x7f0a0044;
        public static final int flsdk_manager_account_name=0x7f0a0043;
        public static final int flsdk_manager_account_set_account=0x7f0a0046;
        public static final int flsdk_manager_account_split_line=0x7f0a0048;
        public static final int flsdk_manager_account_switch=0x7f0a0049;
        public static final int flsdk_menu_settings=0x7f0a0075;
        public static final int flsdk_qq_login=0x7f0a0041;
        public static final int flsdk_register_account_lay=0x7f0a0050;
        public static final int flsdk_register_account_tip=0x7f0a0051;
        public static final int flsdk_register_btn=0x7f0a0058;
        public static final int flsdk_register_new_pwd_lay=0x7f0a0052;
        public static final int flsdk_register_new_pwd_tip=0x7f0a0053;
        public static final int flsdk_register_protocal_checkbox=0x7f0a0056;
        public static final int flsdk_register_protocal_text=0x7f0a0057;
        public static final int flsdk_register_pwd_check_lay=0x7f0a0055;
        public static final int flsdk_register_single_btn=0x7f0a004f;
        public static final int flsdk_register_sure_pwd_lay=0x7f0a0054;
        public static final int flsdk_resetpwd_code_lay=0x7f0a0059;
        public static final int flsdk_resetpwd_new_pwd_lay=0x7f0a005a;
        public static final int flsdk_resetpwd_new_pwd_tip=0x7f0a005b;
        public static final int flsdk_resetpwd_pwd_check_lay=0x7f0a005d;
        public static final int flsdk_resetpwd_sure_pwd_lay=0x7f0a005c;
        public static final int flsdk_sina_login=0x7f0a0042;
        public static final int flsdk_third_sina_account_icon=0x7f0a0062;
        public static final int flsdk_third_sina_account_name=0x7f0a0063;
        public static final int flsdk_third_sina_quanxian=0x7f0a0064;
        public static final int flsdk_third_sina_switch_btn=0x7f0a0061;
        public static final int flsdk_title=0x7f0a0011;
        public static final int flsdk_title_btn=0x7f0a001a;
        public static final int flsdk_title_right_btn=0x7f0a001c;
        public static final int flsdk_title_text=0x7f0a001b;
        public static final int flsdk_toast_message=0x7f0a0065;
        public static final int flsdk_tool_bar=0x7f0a0066;
        public static final int flsdk_tool_bar_expand=0x7f0a0069;
        public static final int flsdk_verify_again_lay=0x7f0a005e;
        public static final int flsdk_verify_count_down_btn=0x7f0a000f;
        public static final int flsdk_webview=0x7f0a0070;
        public static final int flsdkk_base_edit_clear=0x7f0a0016;
        public static final int flskd_manager_account_security_tips=0x7f0a004a;
        public static final int guest_login_button=0x7f0a0002;
        public static final int iv_icon=0x7f0a0071;
        public static final int textView1=0x7f0a0000;
        public static final int tv_nickname_lzz=0x7f0a0072;
        public static final int user_login_button=0x7f0a0003;
        public static final int vertical_screen_checkBox=0x7f0a0001;
    }
    public static final class layout {
        public static final int activity_welcome=0x7f030000;
        public static final int flsdk_alert_dialog=0x7f030001;
        public static final int flsdk_band_layout_land=0x7f030002;
        public static final int flsdk_band_layout_port=0x7f030003;
        public static final int flsdk_base_bg_layout_land=0x7f030004;
        public static final int flsdk_base_bg_layout_port=0x7f030005;
        public static final int flsdk_base_checkbox_layout=0x7f030006;
        public static final int flsdk_base_divide_line_img=0x7f030007;
        public static final int flsdk_base_divide_line_layout=0x7f030008;
        public static final int flsdk_base_edit_layout=0x7f030009;
        public static final int flsdk_base_loading_layout=0x7f03000a;
        public static final int flsdk_base_title_layout=0x7f03000b;
        public static final int flsdk_base_username_layout=0x7f03000c;
        public static final int flsdk_drop_builder_layout=0x7f03000d;
        public static final int flsdk_editpwd_layout_land=0x7f03000e;
        public static final int flsdk_editpwd_layout_port=0x7f03000f;
        public static final int flsdk_findpwd_layout_land=0x7f030010;
        public static final int flsdk_findpwd_layout_port=0x7f030011;
        public static final int flsdk_function_content_layout=0x7f030012;
        public static final int flsdk_function_layout=0x7f030013;
        public static final int flsdk_invitation_layout_land=0x7f030014;
        public static final int flsdk_invitation_layout_port=0x7f030015;
        public static final int flsdk_login_account_layout=0x7f030016;
        public static final int flsdk_login_btn_layout_land=0x7f030017;
        public static final int flsdk_login_btn_layout_port=0x7f030018;
        public static final int flsdk_login_drop_builder_item_layout=0x7f030019;
        public static final int flsdk_login_layout_land=0x7f03001a;
        public static final int flsdk_login_layout_port=0x7f03001b;
        public static final int flsdk_login_pwd_edit_layout=0x7f03001c;
        public static final int flsdk_login_third_layout_land=0x7f03001d;
        public static final int flsdk_login_third_layout_port=0x7f03001e;
        public static final int flsdk_manager_account_layout_land=0x7f03001f;
        public static final int flsdk_manager_account_layout_port=0x7f030020;
        public static final int flsdk_register_button_layout=0x7f030021;
        public static final int flsdk_register_drop_builder_header_layout=0x7f030022;
        public static final int flsdk_register_drop_builder_item_layout=0x7f030023;
        public static final int flsdk_register_layout_land=0x7f030024;
        public static final int flsdk_register_layout_port=0x7f030025;
        public static final int flsdk_register_protocal_layout=0x7f030026;
        public static final int flsdk_register_pwd_edit_layout=0x7f030027;
        public static final int flsdk_resetpwd_layout_land=0x7f030028;
        public static final int flsdk_resetpwd_layout_port=0x7f030029;
        public static final int flsdk_resetpwd_verify_layout=0x7f03002a;
        public static final int flsdk_test_entry=0x7f03002b;
        public static final int flsdk_third_sina_layout_land=0x7f03002c;
        public static final int flsdk_third_sina_layout_port=0x7f03002d;
        public static final int flsdk_toast_layout=0x7f03002e;
        public static final int flsdk_toolbar_layout=0x7f03002f;
        public static final int flsdk_webview_layout_land=0x7f030030;
        public static final int flsdk_webview_layout_port=0x7f030031;
        public static final int main=0x7f030032;
    }
    public static final class menu {
        public static final int flsdk_activity_main=0x7f090000;
    }
    public static final class raw {
        public static final int parent=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f070001;
        public static final int flsdk_app_name=0x7f070003;
        /**  begin 
         */
        public static final int flsdk_game_html_template_begin=0x7f070006;
        /**  end 
         */
        public static final int flsdk_game_html_template_end=0x7f070007;
        public static final int flsdk_hello_world=0x7f070004;
        public static final int flsdk_menu_settings=0x7f070005;
        public static final int hello_world=0x7f070002;
        public static final int title_activity_welcome=0x7f070000;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
        public static final int flsdk_AppTheme=0x7f080002;
        public static final int flsdk_style_077df7_14=0x7f08000b;
        public static final int flsdk_style_494e54_18=0x7f080004;
        public static final int flsdk_style_9a9a9a_14=0x7f080012;
        public static final int flsdk_style_body_lay=0x7f080013;
        public static final int flsdk_style_body_lay_port=0x7f080014;
        public static final int flsdk_style_btn_blue=0x7f080019;
        public static final int flsdk_style_btn_green=0x7f080016;
        public static final int flsdk_style_btn_green_test=0x7f08001a;
        public static final int flsdk_style_btn_unable=0x7f080018;
        public static final int flsdk_style_btn_yellow=0x7f080017;
        public static final int flsdk_style_c12c20_14=0x7f080009;
        public static final int flsdk_style_c2c2c2_14=0x7f080008;
        public static final int flsdk_style_c2c2c2_18=0x7f080003;
        public static final int flsdk_style_d5bf00_14=0x7f08000a;
        public static final int flsdk_style_d5bf00_18=0x7f08000f;
        public static final int flsdk_style_edit_text=0x7f080011;
        public static final int flsdk_style_f1e74b_11=0x7f08000c;
        public static final int flsdk_style_f7d98b_14=0x7f08000d;
        public static final int flsdk_style_ffffff_14=0x7f08000e;
        public static final int flsdk_style_ffffff_18=0x7f080005;
        public static final int flsdk_style_msg_tips=0x7f080006;
        public static final int flsdk_style_title_text=0x7f080010;
        public static final int flsdk_style_translucent_lay=0x7f080015;
        public static final int flsdk_style_white_14=0x7f080007;
    }
}
